monolog:
    channels:
        - 'deprecation'
        - 'mail'
        - 'queue'
    handlers:
        mail:
            max_files: 30
            level: 'debug'
            type: 'rotating_file'
            path: '%kernel.logs_dir%/%kernel.environment%_mail.log'
            channels: 'mail'
        queue:
            max_files: 30
            level: 'debug'
            type: 'rotating_file'
            path: '%kernel.logs_dir%/%kernel.environment%_queue.log'
            channels: 'queue'

when@dev:
    monolog:
        handlers:
            main:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: 'debug'
                max_files: 10
                channels: [ '!event' ]
            console:
                type: 'console'
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine', '!console' ]

when@test:
    monolog:
        handlers:
            main:
                type: 'fingers_crossed'
                action_level: 'error'
                handler: 'nested'
                excluded_http_codes: [ 404, 405 ]
                channels: [ '!event' ]
            nested:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: 'debug'
                max_files: 1

when@prod:
    monolog:
        handlers:
            queue:
                level: 'info'
            main:
                type: 'fingers_crossed'
                action_level: 'error'
                handler: 'nested'
                excluded_http_codes: [ 404, 405 ]
                channels: [ '!deprecation' ]
                buffer_size: 50
            nested:
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                type: 'rotating_file'
                level: 'debug'
                max_files: 15
                channels: [ '!deprecation' ]
            console:
                type: 'console'
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine' ]
            deprecation:
                type: 'stream'
                channels: [ 'deprecation' ]
                path: 'php://stderr'
                formatter: 'monolog.formatter.json'
