services:
    admin.category:
        class: 'App\Admin\CategoryAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Category', controller: ~, manager_type: 'orm', group: 'Content', label: 'Categories' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
    admin.project:
        class: 'App\Admin\ProjectAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Project', controller: 'App\Controller\Admin\ProjectAdminController', manager_type: 'orm', group: 'Content', label: 'Projects' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
    admin.project_image:
        class: 'App\Admin\Image\ProjectImageAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Image\ProjectImage', controller: ~, manager_type: 'orm', group: 'Content', label: 'Extra Pictures' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
#    admin.contact_message:
#        class: 'App\Admin\ContactMessageAdmin'
#        tags:
#            - { name: 'sonata.admin', model_class: 'App\Entity\ContactMessage', controller: 'App\Controller\Admin\ContactMessageAdminController', manager_type: 'orm', group: 'Contact', label: 'Contact Message', show_in_dashboard: true }
#        calls:
#            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
